name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: 'x64'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install PyInstaller
        python -m pip install -r requirements.txt
    - name: Build
      shell: bash
      run: |
        mkdir -p dist/migaku_mpv
        pyinstaller -F --distpath dist/migaku_mpv -n migaku_mpv -i icon.ico migaku_mpv.py
        cp -r icons modules main.lua migaku_mpv.cfg migaku_mpv.html dist/migaku_mpv/
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-ubuntu-latest-x64
        path: dist/*
